name: my_progress_bar
description: "A flutter package for displaying progress bars and loaders."
version: 2.1.0
homepage: https://github.com/adnanflutterdev/my_progress_bar.git
license: MIT

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: